name: release

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: build
        run: |
          npm ci
          npm run build
      - name: upload bookmarklet release
        id: upload-bookmarklet-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/bookmarklet
          asset_name: bookmarklet
          asset_content_type: text/plain
